In [1]:
import tensorflow as tf
from tensorflow.keras import layers
import random
import numpy as np
import json
import spacy

In [2]:
nlp = spacy.load("en_core_web_sm")

In [3]:
d = open('data.json')
json_data = json.load(d)
json_data

{'intends': [{'tag': ['greating'],
   'question': ['hello', "what's up", 'hey', 'hi', 'hey there'],
   'answer': ['Hi!']},
  {'tag': ['name'],
   'question': ['what is your name',
    'introduce',
    'introduce yourself',
    'who',
    'name',
    'who are you'],
   'answer': ['My name is Prajwal Bhandari']},
  {'tag': ['health'],
   'question': ['how are you', 'fine', 'how is your health', 'health'],
   'answer': ["Yes I'm fine!"]},
  {'tag': ['situation'],
   'question': ['how is it going',
    'are you okay',
    'how do you do',
    'are you good',
    'how is your study going on'],
   'answer': ['Thikai!']},
  {'tag': ['address'],
   'question': ['where do you live',
    'home',
    'where is your home',
    'what is your address',
    'address'],
   'answer': ['I live in Tilottama, Nepal']},
  {'tag': ['college'],
   'question': ['where do you study',
    'college',
    'which university do you study',
    'university'],
   'answer': ['Nepathya College affiliated to Tribhuvan U

In [4]:
ques = []
document = []
classes = []


for intents in json_data['intends']:
    for question in intents['question']:
        print(question)
        
        doc = nlp(question.lower())
        text = [token.lemma_ for token in doc]
        
       
        ques.append(text)
        document.append(( text, intents['tag']))

        
        
    for question in intents['tag']:
#         print(question)
        if question not in list(classes):
            classes.append(question)
        

hello
what's up
hey
hi
hey there
what is your name
introduce
introduce yourself
who
name
who are you
how are you
fine
how is your health
health
how is it going
are you okay
how do you do
are you good
how is your study going on
where do you live
home
where is your home
what is your address
address
where do you study
college
which university do you study
university
what do you study
subject
what is your major
bye
goodbye
later
see you next time
see you later
take care
your current location
where
location
where are you


In [5]:
random.shuffle(document)
document

[(['your', 'current', 'location'], ['location']),
 (['how', 'be', 'it', 'go'], ['situation']),
 (['hello'], ['greating']),
 (['hi'], ['greating']),
 (['home'], ['address']),
 (['where', 'do', 'you', 'live'], ['address']),
 (['hey'], ['greating']),
 (['where', 'be', 'you'], ['location']),
 (['how', 'do', 'you', 'do'], ['situation']),
 (['university'], ['college']),
 (['see', 'you', 'next', 'time'], ['goodbye']),
 (['take', 'care'], ['goodbye']),
 (['be', 'you', 'good'], ['situation']),
 (['name'], ['name']),
 (['what', 'be', 'your', 'address'], ['address']),
 (['college'], ['college']),
 (['what', 'be', 'your', 'name'], ['name']),
 (['how', 'be', 'your', 'study', 'go', 'on'], ['situation']),
 (['be', 'you', 'okay'], ['situation']),
 (['what', 'be', 'up'], ['greating']),
 (['later'], ['goodbye']),
 (['how', 'be', 'your', 'health'], ['health']),
 (['introduce', 'yourself'], ['name']),
 (['see', 'you', 'later'], ['goodbye']),
 (['who'], ['name']),
 (['which', 'university', 'do', 'you', 'st

In [6]:
classes

['greating',
 'name',
 'health',
 'situation',
 'address',
 'college',
 'education',
 'goodbye',
 'location']

In [7]:
ques = [" ".join(i[0]) for i in document]
ques[10:]


['see you next time',
 'take care',
 'be you good',
 'name',
 'what be your address',
 'college',
 'what be your name',
 'how be your study go on',
 'be you okay',
 'what be up',
 'later',
 'how be your health',
 'introduce yourself',
 'see you later',
 'who',
 'which university do you study',
 'bye',
 'fine',
 'where',
 'how be you',
 'where be your home',
 'what be your major',
 'introduce',
 'health',
 'location',
 'goodbye',
 'subject',
 'where do you study',
 'who be you',
 'hey there',
 'address',
 'what do you study']

In [8]:
ans = ["".join(i[1]) for i in document]
ans

['location',
 'situation',
 'greating',
 'greating',
 'address',
 'address',
 'greating',
 'location',
 'situation',
 'college',
 'goodbye',
 'goodbye',
 'situation',
 'name',
 'address',
 'college',
 'name',
 'situation',
 'situation',
 'greating',
 'goodbye',
 'health',
 'name',
 'goodbye',
 'name',
 'college',
 'goodbye',
 'health',
 'location',
 'health',
 'address',
 'education',
 'name',
 'health',
 'location',
 'goodbye',
 'education',
 'college',
 'name',
 'greating',
 'address',
 'education']

In [9]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse=False)

train_one_hot = ohe.fit_transform(np.array(ans).reshape(-1,1))
train_one_hot

c:\Users\USER\Documents\ML\NLP\bot\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0.

In [10]:
train_ques = ques[:30]
train_ans = train_one_hot[:30]

val_ques = ques[30:]
val_ans = train_one_hot[30:]

len(train_ques)

30

In [11]:
train_datasets = tf.data.Dataset.from_tensor_slices((train_ques, train_ans)).batch(32).prefetch(tf.data.AUTOTUNE)
val_datasets = tf.data.Dataset.from_tensor_slices((val_ques, val_ans)).batch(32).prefetch(tf.data.AUTOTUNE)


train_datasets

<_PrefetchDataset element_spec=(TensorSpec(shape=(None,), dtype=tf.string, name=None), TensorSpec(shape=(None, 9), dtype=tf.float64, name=None))>

In [12]:
max_vocab = 10000
output_length = 200

text_vector = layers.TextVectorization(max_tokens = max_vocab+1 , output_sequence_length=output_length )

text_embed = layers.Embedding(max_vocab, 128, mask_zero=True)

text_vector.adapt(ques)

In [46]:
inputs = layers.Input(shape = (1,), dtype = tf.string)
vector = text_vector(inputs)
embed = text_embed(vector)
first_dense = layers.Dense(264, activation = "relu")(embed)
lstm_rnn = layers.Bidirectional(layers.LSTM(512), name = "LSTM_layer")(first_dense)

x = layers.Dropout(0.1)(lstm_rnn)
x = layers.Dense(264, activation = "relu")(x)
simple_output = layers.Dense(len(classes), activation = "softmax")(x)

simple_model = tf.keras.Model(inputs, simple_output)


bi_rnn = layers.Bidirectional(layers.GRU(512), name = "GRU_layer")(first_dense)
x = layers.Dropout(0.1)(bi_rnn)
x = layers.Dense(264, activation = "relu")(x)
bi_output = layers.Dense(len(classes), activation = "softmax")(x)
bi_model = tf.keras.Model(inputs, bi_output)

x = layers.Concatenate()([simple_model.output, bi_model.output])
x = layers.Dense(264 , activation = "relu")(x)
x = layers.Dropout(0.1)(x)
x = layers.Dense(264 , activation = "relu")(x)
x = layers.Dense(264 , activation = "relu")(x)


outputs = layers.Dense(len(classes), activation = "softmax")(x)

model_0 = tf.keras.Model(inputs , outputs)

model_0.summary()

Model: "model_28"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_13 (InputLayer)          [(None, 1)]          0           []                               
                                                                                                  
 text_vectorization (TextVector  (None, 200)         0           ['input_13[0][0]']               
 ization)                                                                                         
                                                                                                  
 embedding (Embedding)          (None, 200, 128)     1280000     ['text_vectorization[12][0]']    
                                                                                                  
 dense_70 (Dense)               (None, 200, 264)     34056       ['embedding[12][0]']      

In [47]:
model_0.compile(loss = "categorical_crossentropy",
               optimizer = "adam",
               metrics = ["accuracy"])

model_0_history = model_0.fit(train_datasets, 
           epochs = 25, validation_data = val_datasets )

Epoch 1/25
1/1 [==============================] - 44s 44s/step - loss: 2.2007 - accuracy: 0.1333 - val_loss: 2.1988 - val_accuracy: 0.1667
Epoch 2/25
1/1 [==============================] - 11s 11s/step - loss: 2.1916 - accuracy: 0.1333 - val_loss: 2.2075 - val_accuracy: 0.1667
Epoch 3/25
1/1 [==============================] - 11s 11s/step - loss: 2.1823 - accuracy: 0.1000 - val_loss: 2.2165 - val_accuracy: 0.1667
Epoch 4/25
1/1 [==============================] - 12s 12s/step - loss: 2.1763 - accuracy: 0.1333 - val_loss: 2.2263 - val_accuracy: 0.1667
Epoch 5/25
1/1 [==============================] - 11s 11s/step - loss: 2.1670 - accuracy: 0.2333 - val_loss: 2.2379 - val_accuracy: 0.1667
Epoch 6/25
1/1 [==============================] - 13s 13s/step - loss: 2.1591 - accuracy: 0.2667 - val_loss: 2.2518 - val_accuracy: 0.0833
Epoch 7/25
1/1 [==============================] - 12s 12s/step - loss: 2.1481 - accuracy: 0.2000 - val_loss: 2.2690 - val_accuracy: 0.0833
Epoch 8/25
1/1 [===========

In [48]:
ask = "hi"

pred = model_0.predict(np.array(list(ask)))
pred

1/1 [==============================] - 9s 9s/step


array([[0.10132478, 0.09836511, 0.00911176, 0.1187767 , 0.1420282 ,
        0.09863354, 0.1093633 , 0.1582581 , 0.16413857],
       [0.10132478, 0.09836511, 0.00911176, 0.1187767 , 0.1420282 ,
        0.09863354, 0.1093633 , 0.1582581 , 0.16413857]], dtype=float32)

In [50]:
ask = "where"

pred = model_0.predict(np.array(list(ask)))
pred

1/1 [==============================] - 1s 1s/step


array([[0.10132478, 0.09836511, 0.00911176, 0.1187767 , 0.1420282 ,
        0.09863354, 0.1093633 , 0.1582581 , 0.16413857],
       [0.10132478, 0.09836511, 0.00911176, 0.1187767 , 0.1420282 ,
        0.09863354, 0.1093633 , 0.1582581 , 0.16413857],
       [0.10132478, 0.09836511, 0.00911176, 0.1187767 , 0.1420282 ,
        0.09863354, 0.1093633 , 0.1582581 , 0.16413857],
       [0.10132478, 0.09836511, 0.00911176, 0.1187767 , 0.1420282 ,
        0.09863354, 0.1093633 , 0.1582581 , 0.16413857],
       [0.10132478, 0.09836511, 0.00911176, 0.1187767 , 0.1420282 ,
        0.09863354, 0.1093633 , 0.1582581 , 0.16413857]], dtype=float32)

In [31]:
pred = tf.argmax(pred,1)
pred

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([4, 4], dtype=int64)>

In [17]:
classes

['greating',
 'name',
 'health',
 'situation',
 'address',
 'college',
 'education',
 'goodbye',
 'location']