In [1]:
import tensorflow as tf
from tensorflow.keras import layers
import random
import numpy as np
import json
import spacy

In [2]:
nlp = spacy.load("en_core_web_sm")

In [3]:
d = open('data.json')
json_data = json.load(d)
json_data

{'intends': [{'tag': ['greating'],
   'question': ['hello', "what's up", 'hey'],
   'answer': ['Hi!']},
  {'tag': ['name'],
   'question': ['what is your name',
    'nam k ho',
    'ko ho',
    'ko hos',
    'who are you'],
   'answer': ['My name is Prajwal Bhandari']},
  {'tag': ['health'],
   'question': ['how are you', 'sanchai xau', 'sanchai', 'thikai'],
   'answer': ["Yes I'm fine!"]},
  {'tag': ['situation'],
   'question': ['k xa',
    'are you okay',
    'how do you do',
    'are you good',
    'how is your study going on',
    'padai kasto xa tw'],
   'answer': ['Thikai!']},
  {'tag': ['address'],
   'question': ['where do you live', 'ka basxau', 'ghar kaha ho', 'ghar'],
   'answer': ['I live in Tilottama, Nepal']},
  {'tag': ['college'],
   'question': ['where do you study', 'college', 'ka padxas', 'padxas'],
   'answer': ['Nepathya College affiliated to Tribhuvan University']},
  {'tag': ['education'],
   'question': ['what do you study', 'k padxau'],
   'answer': ['Bachelor

In [4]:
ques = []
document = []
classes = []


for intents in json_data['intends']:
    for question in intents['question']:
        print(question)
        
        doc = nlp(question.lower())
        text = [token.lemma_ for token in doc]
        
       
        ques.append(text)
        document.append(( text, intents['tag']))

        
        
    for question in intents['tag']:
#         print(question)
        if question not in list(classes):
            classes.append(question)
        

hello
what's up
hey
what is your name
nam k ho
ko ho
ko hos
who are you
how are you
sanchai xau
sanchai
thikai
k xa
are you okay
how do you do
are you good
how is your study going on
padai kasto xa tw
where do you live
ka basxau
ghar kaha ho
ghar
where do you study
college
ka padxas
padxas
what do you study
k padxau
bye
goodbye
tata
paxi bhetamla
see you later
take care


In [5]:
random.shuffle(document)
document

[(['what', 'be', 'up'], ['greating']),
 (['what', 'do', 'you', 'study'], ['education']),
 (['take', 'care'], ['goodbye']),
 (['where', 'do', 'you', 'live'], ['address']),
 (['who', 'be', 'you'], ['name']),
 (['ko', 'hos'], ['name']),
 (['ghar'], ['address']),
 (['padxas'], ['college']),
 (['be', 'you', 'okay'], ['situation']),
 (['see', 'you', 'later'], ['goodbye']),
 (['padai', 'kasto', 'xa', 'tw'], ['situation']),
 (['paxi', 'bhetamla'], ['goodbye']),
 (['how', 'be', 'your', 'study', 'go', 'on'], ['situation']),
 (['sanchai', 'xau'], ['health']),
 (['nam', 'k', 'ho'], ['name']),
 (['ghar', 'kaha', 'ho'], ['address']),
 (['college'], ['college']),
 (['ka', 'basxau'], ['address']),
 (['hey'], ['greating']),
 (['k', 'padxau'], ['education']),
 (['tata'], ['goodbye']),
 (['hello'], ['greating']),
 (['where', 'do', 'you', 'study'], ['college']),
 (['what', 'be', 'your', 'name'], ['name']),
 (['thikai'], ['health']),
 (['bye'], ['goodbye']),
 (['how', 'do', 'you', 'do'], ['situation']),
 (

In [6]:
classes

['greating',
 'name',
 'health',
 'situation',
 'address',
 'college',
 'education',
 'goodbye']

In [7]:
ques = [" ".join(i[0]) for i in document]
ques[10:]


['padai kasto xa tw',
 'paxi bhetamla',
 'how be your study go on',
 'sanchai xau',
 'nam k ho',
 'ghar kaha ho',
 'college',
 'ka basxau',
 'hey',
 'k padxau',
 'tata',
 'hello',
 'where do you study',
 'what be your name',
 'thikai',
 'bye',
 'how do you do',
 'sanchai',
 'k xa',
 'ka padxas',
 'be you good',
 'how be you',
 'goodbye',
 'ko ho']

In [8]:
ans = ["".join(i[1]) for i in document]
ans

['greating',
 'education',
 'goodbye',
 'address',
 'name',
 'name',
 'address',
 'college',
 'situation',
 'goodbye',
 'situation',
 'goodbye',
 'situation',
 'health',
 'name',
 'address',
 'college',
 'address',
 'greating',
 'education',
 'goodbye',
 'greating',
 'college',
 'name',
 'health',
 'goodbye',
 'situation',
 'health',
 'situation',
 'college',
 'situation',
 'health',
 'goodbye',
 'name']

In [9]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse=False)

train_one_hot = ohe.fit_transform(np.array(ans).reshape(-1,1))
train_one_hot

c:\Users\USER\Documents\ML\NLP\bot\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 

In [10]:
train_datasets = tf.data.Dataset.from_tensor_slices((ques, train_one_hot)).batch(32).prefetch(tf.data.AUTOTUNE)
train_datasets

<_PrefetchDataset element_spec=(TensorSpec(shape=(None,), dtype=tf.string, name=None), TensorSpec(shape=(None, 8), dtype=tf.float64, name=None))>

In [11]:
max_vocab = 1000
output_length = 100

text_vector = layers.TextVectorization(max_tokens = max_vocab+1 , output_sequence_length=output_length )

text_embed = layers.Embedding(max_vocab, 128, mask_zero=True)

text_vector.adapt(ques)

In [12]:
inputs = layers.Input(shape = (1,), dtype = tf.string)
vector = text_vector(inputs)
embed = text_embed(vector)
x = layers.Dense(500, activation = "relu")(embed)
x = layers.Dropout(0.1)(x)
x = layers.Bidirectional(layers.LSTM(500), name = "Bidirectional_layer")(x)
x = layers.Dropout(0.1)(x)

x = layers.Dense(500 , activation = "relu")(x)
x = layers.Dropout(0.1)(x)


outputs = layers.Dense(len(classes), activation = "softmax")(x)

model_0 = tf.keras.Model(inputs , outputs)

model_0.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization (TextVec  (None, 100)              0         
 torization)                                                     
                                                                 
 embedding (Embedding)       (None, 100, 128)          128000    
                                                                 
 dense (Dense)               (None, 100, 500)          64500     
                                                                 
 dropout (Dropout)           (None, 100, 500)          0         
                                                                 
 Bidirectional_layer (Bidire  (None, 1000)             4004000   
 ctional)                                                    

In [13]:
model_0.compile(loss = "categorical_crossentropy",
               optimizer = "adam",
               metrics = ["accuracy"])

model_0_history = model_0.fit(train_datasets, 
           epochs = 25 )

Epoch 1/25
2/2 [==============================] - 29s 1s/step - loss: 2.0798 - accuracy: 0.0000e+00
Epoch 2/25
2/2 [==============================] - 5s 1s/step - loss: 2.0564 - accuracy: 0.3529
Epoch 3/25
2/2 [==============================] - 5s 2s/step - loss: 2.0277 - accuracy: 0.2059
Epoch 4/25
2/2 [==============================] - 7s 2s/step - loss: 1.9835 - accuracy: 0.2059
Epoch 5/25
2/2 [==============================] - 13s 3s/step - loss: 1.9268 - accuracy: 0.1765
Epoch 6/25
2/2 [==============================] - 15s 3s/step - loss: 1.8998 - accuracy: 0.2059
Epoch 7/25
2/2 [==============================] - 11s 2s/step - loss: 1.8822 - accuracy: 0.2059
Epoch 8/25
2/2 [==============================] - 9s 1s/step - loss: 1.7952 - accuracy: 0.2941
Epoch 9/25
2/2 [==============================] - 9s 3s/step - loss: 1.6453 - accuracy: 0.4706
Epoch 10/25
2/2 [==============================] - 10s 1s/step - loss: 1.5048 - accuracy: 0.4118
Epoch 11/25
2/2 [=======================

In [36]:
ask = "hello"

pred = model_0.predict(np.array(list(ask)))
pred

1/1 [==============================] - 0s 354ms/step


array([[0.11045629, 0.03133829, 0.025288  , 0.24579218, 0.21640883,
        0.08141471, 0.21370453, 0.07559713],
       [0.11045629, 0.03133829, 0.025288  , 0.24579218, 0.21640883,
        0.08141471, 0.21370453, 0.07559713],
       [0.11045629, 0.03133829, 0.025288  , 0.24579218, 0.21640883,
        0.08141471, 0.21370453, 0.07559713],
       [0.11045629, 0.03133829, 0.025288  , 0.24579218, 0.21640883,
        0.08141471, 0.21370453, 0.07559713],
       [0.11045629, 0.03133829, 0.025288  , 0.24579218, 0.21640883,
        0.08141471, 0.21370453, 0.07559713]], dtype=float32)

In [35]:
pred = tf.argmax(pred,1)
pred

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([3, 3, 3], dtype=int64)>

In [15]:
classes

['greating',
 'name',
 'health',
 'situation',
 'address',
 'college',
 'education',
 'goodbye']